project:
  type: website

website:
  title: "Qualitative guide for R"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - icon: github
        href: https://github.com/tidy-MN/qualitative-guide
format:
  html:
    theme: minty
    css: styles.css



